# Generated by Django 4.1 on 2022-11-02 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=75, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ruas',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=75, null=True)),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rua')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Festivais',
            },
        ),
    ]
